# Generated by Django 2.2.1 on 2019-05-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_caunam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cauhai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cau2/')),
            ],
        ),
    ]
